### ISSUE TITLE
CSS not reloaded - invalid command 'reload', only valid commands are: hello

### ISSUE THREAD

**Issue by janisit** [guard/guard-livereload#133] opened 2015-02-23 14:01 UTC
Hi,

I am getting this JavaScript error in my browser:
 LiveReload protocol error (invalid command 'reload', only valid commands are: hello)) after receiving data: "{"command":"reload","path":"/home/web/public_html/css/style.css","liveCSS":true}"..

The used gem versions are:
guard 2.12.3
guard-compass 1.1.0
guard-livereload 2.4.0
guard-shell 0.6.1

Any ideas?

Regards,
Janis

**Comment by e2** [comment] 2015-02-23 23:12
Run Guard with the '-d' option and paste the output. You should see "Browser connected" and the data sent.

Explanation (may help):

"hello" is a special command used to tell LiveReload what protocol to use - and this "hello" command is sent after a browser is connect to the livereload server. So make sure:

1. You start the server first (`bundle exec guard -d`)
2. You connect with a Browser (usually you have to enable by clicking the LiveReload icon in the browser toolbar)
3. You should see "Browser connected" (this is when the protocol is set through the "hello" command)
4. Now reloading should work - if not, paste the output.

**Comment by janisit** [comment] 2015-02-24 09:52
I thought that it was enough to include
<script src="http://mydomain.com:35729/livereload.js">/script>
and you didn't need to install any browser extensions. Anyway, I tried to install Chrome Livereload extension, but it is unable to connect (perhaps because the website is not hosted on my computer and scss files are updated via SFTP).

here is an output of bundle exec guard -d

11:36:48 - DEBUG - Command execution: hash stty
11:36:48 - DEBUG - Guard starts all plugins
11:36:48 - DEBUG - Hook :start_begin executed for Guard::Compass
11:36:48 - INFO - Guard::Compass is waiting to compile your stylesheets.
11:36:48 - DEBUG - Hook :start_end executed for Guard::Compass
11:36:48 - DEBUG - Hook :start_begin executed for Guard::LiveReload
11:36:48 - DEBUG - Hook :start_end executed for Guard::LiveReload
11:36:48 - INFO - LiveReload is waiting for a browser to connect.
11:36:48 - INFO - Guard is now watching at '/home/web/public_html'
11:36:48 - DEBUG - Start interactor
[1] guard(main)> 11:36:50 - INFO - Browser connected.
11:36:59 - DEBUG - Serving file /home/web/bundle/gems/guard-livereload-2.4.0/js/livereload.js
11:37:29 - DEBUG - Interactor was stopped or killed
11:37:29 - DEBUG - Hook :run_on_change_begin executed for Guard::Compass
    write css/style.css
    write css/style.css.map
11:37:35 - DEBUG - Hook :run_on_change_end executed for Guard::Compass
11:37:35 - DEBUG - Hook :run_on_modifications_begin executed for Guard::LiveReload
11:37:35 - INFO - Reloading browser: css/style.css
11:37:35 - DEBUG - {:command=>"reload", :path=>"/home/web/public_html/css/style.css", :liveCSS          =>true}
11:37:35 - DEBUG - Hook :run_on_modifications_end executed for Guard::LiveReload
11:37:35 - DEBUG - Start interactor
[1] guard(main)> 11:38:25 - DEBUG - Serving file /home/web/bundle/gems/guard-livereload-2.4.0/js/livereload.js

And this is the error I get in the Chrome console:
LiveReload protocol error (invalid command 'reload', only valid commands are: hello)) after receiving data: "{"command":"reload","path":"/home/web/public_html/css/style.css","liveCSS":true}" livereload.js:867

I get the same thing using Firefox.

Regards,
Janis

**Comment by e2** [comment] 2015-02-26 11:24
I'd suggest using: https://github.com/johnbintz/rack-livereload if you can, since that should automatically create the right snippet and you can configure the host and port. It may be just that the snippet is wrong (I'm not a LiveReload expert and I don't know what is "recommended" vs "outdated").

Aside from that, you may just want to simply debug the script to see what's going on - even just tweaking https://github.com/guard/guard-livereload/blob/master/js/livereload.js until you get it working.

Details:

For some reason, the protocol is not set - I'm guessing the protocol is cleared in your setup (see livereload.js). `guard-livereload` and `livereload.js` try to "handshake" on a protocol version (6 or 7), which guard-livereload supporting only 7. 

So, the protocol should be set to `7` before any reload command happens. The protocol is set with "hello" commands (as soon as the websocket is connected) and cleared during disconnects (and refreshes I guess) - so you may want to make sure the protocol is set (by debugging livereload.js in the browser) and make sure it isn't cleared/disconnected/etc..

It could be just a bad snippet (I'm not sure what's recommended), so check out the rack-livereload option first.

**Comment by janisit** [comment] 2015-02-26 12:11
Thanks for your help e2. I hardcoded the protocol version in livereload.js. So basically I changed

 Parser.prototype.reset = function () {
            return this.protocol = null;
        };

to 

 Parser.prototype.reset = function () {
            return this.protocol = 7;
        };


Hacking the livereload.js isn't prettiest way of doing it, but it worked for me.

**Comment by e2** [comment] 2015-10-26 21:12
Just after "Browser connected" you should see a "hello" command request in your browser's developer tools.

Also, maybe the browser was disconnected meanwhile (there's no message for that).

I'm closing this (because things like this get outdated very quickly), but do open a new issue if it still reoccurs - and I'll add more debugging options to track this down.

If you can, attach a small repo and a use case (just so I accurately reproduce it - it may have to do with keeping the socket alive between hosts).

**Closed by e2** 2015-10-26 21:12 UTC
Labels: Browser Extension
