### ISSUE TITLE
Reload after compile

### ISSUE THREAD

**Issue by wfpaisa** [guard/guard-livereload#107] opened 2014-05-13 19:31 UTC
try LiveReload load after compiling sass

``` ruby
group :development do
  
  if File.exists?("./config.rb")
    # Compile on start.
    puts `compass compile --time --quiet`
    guard :compass do
      watch(%r{(.*)\.s[ac]ss$})
    end
  end

  guard :livereload do
    watch(%r{.+\.(css|js|tpl)$})
    #watch(%r{.+\.(css|js|tpl|scss)$})
  end

end
```

**Comment by jibiel** [comment] 2015-10-25 15:33
Closing this for now as the duplicate of #105.
Please refer to the latter regarding the `Guard::Compass`/`Guard::LiveReload` interplay.

**Closed by jibiel** 2015-10-25 15:33 UTC
Labels: Feedback Required
